name: 🚀 Build Binaries on Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Compile & Upload Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial for uploading assets to a release
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
    - name: 📥 Check out repository
      uses: actions/checkout@v4

    - name: 🐹 Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: 🛠️ Build Compiled Binary Assets
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        BINARY_NAME=hobbydns-${{ matrix.goos }}-${{ matrix.goarch }}
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        go build -v -o $BINARY_NAME main.go

    - name: 📤 Upload Binaries to Release
      uses: softprops/action-gh-release@v2
      with:
        files: hobbydns-${{ matrix.goos }}-${{ matrix.goarch }}*